### ISSUE TITLE
[Feature]: parse methods comments

### ISSUE THREAD

**Issue by leorolland** [Joffref/genz#24]
### What is the feature?

I want to be able to get comments of the Methods, the same as for Attributes.
TODO in code [here](https://github.com/Joffref/genz/blob/master/internal/parser/parser.go#L135)

### What is the solution?

?

### Why is this important?

core feature of GenZ
to be able to read comments on methods

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Joffref** [comment]
I've assigned you the feature, is that okay?

**Comment by leorolland** [comment]
> I've assigned you the feature, is that okay?

Okay, but next time let's toss a coin
