### ISSUE TITLE
[Enhancement]: Display errored test/file on genz test comparison

### ISSUE THREAD

**Issue by leorolland** [Joffref/genz#25]
### What is the problem?

Actual output when running genz tests (via make test-examples) doesn't give information about the context on failure.
```
▶  genz(refacto-generator-to-parse-1-type-only) $ make test-examples
genz test -directory ./examples/ -v
genz: genz test ./examples/
running test in examples/1_validator/test
genz: generating template for type Human
genz: generated buffer (716 bytes)
genz: gofmt-ing buffer
genz: wrote human_validator.gen.go (580 bytes)
running test in examples/2_getters/test
genz: generating template for type Car
genz: generated buffer (142 bytes)
genz: gofmt-ing buffer
genz: wrote car.gen.go (122 bytes)
?   	github.com/Joffref/genz/examples/2_getters/test	[no test files]
running test in examples/3_tests/tests/0_no_getter
genz: generating template for type Car
genz: generated buffer (19 bytes)
genz: gofmt-ing buffer
genz: wrote car.gen.go (13 bytes)
?   	github.com/Joffref/genz/examples/3_tests/tests/0_no_getter	[no test files]
running test in examples/3_tests/tests/1_1_getter
genz: generating template for type Car
genz: generated buffer (75 bytes)
genz: gofmt-ing buffer
genz: wrote car.gen.go (66 bytes)
=== RUN   TestCarGetModel
--- PASS: TestCarGetModel (0.00s)
PASS
ok  	github.com/Joffref/genz/examples/3_tests/tests/1_1_getter	(cached)
genz: Difference between expected.go and generated file:
  []uint8(
  	"""
  	... // 22 identical lines
  		// WORK IN PROGRESS
  	
- 		// map[_0:+>18 _1:<99]
+ 		// map[_0:&#43;&gt;18 _1:&lt;99]
  	
  		return nil
  	... // 2 identical lines
  	"""
  )

make: *** [Makefile:23: test-examples] Error 1
```

### What is the solution?

I guess we can have a best output to read the results
1. Getting `PASS` at the end of unit tests execution even with a failure is a bit tricky because we could understand everything went well, (or is that me ?)
2. I see that somewhere I got a diff `genz: Difference between expected.go and generated file:` but there is no information about the concerned directory or test name (I suggest to print the directory and the test name)
3. (bonus) Maybe we can have a summary at the end ? 

### Why is this important?

Because currently it's hard to determine where a test did not match

### What are the alternatives?

no idea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Joffref** [comment]
I won't be on this right now, but I'm taking the issue :)
