### ISSUE TITLE
[Feature]: get the aliased name of an imported type

### ISSUE THREAD

**Issue by leorolland** [Joffref/genz#40]
### What is the feature?

I want to get the package name qualifier following the aliased name I gave in the parsed go input

### What is the solution?

A solution happened!

### Why is this important?

A reason happened!

### What are the alternatives?

An alternative happened!

### What is the impact?

An impact happened!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Joffref** [comment]
As discussed, this a concern of the user rather than something to consider in GenZ.
